# Generated by Django 4.2 on 2024-05-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IranPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=9, verbose_name='Номер паспорта')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('father_name', models.CharField(max_length=30, verbose_name='Имя отца')),
                ('birthday', models.CharField(max_length=30, verbose_name='Дата рождения')),
                ('place_of_birthday', models.CharField(max_length=30, verbose_name='Место рождения')),
                ('sex', models.CharField(max_length=30, verbose_name='Пол')),
                ('date_of_issue', models.CharField(max_length=30, verbose_name='Дата выдачи')),
                ('date_of_expiry', models.CharField(max_length=30, verbose_name='Действителен до')),
                ('lond_number', models.CharField(max_length=30, verbose_name='Длинный номер')),
            ],
        ),
    ]
