# Generated by Django 4.2 on 2024-06-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filler', '0003_iranpassport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iranpassport',
            name='image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
