# Generated by Django 4.2 on 2024-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filler', '0004_alter_iranpassport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='iranpassport',
            name='issuing_authority',
            field=models.CharField(choices=[('authority1', 'Бригадный генерал\nАли Золгадри'), ('authority2', 'Бригадный генерал\nСадэг Резадуст')], default='authority1', max_length=10, verbose_name='Имя и должность должностного лица'),
        ),
    ]
