# Generated by Django 5.0.7 on 2024-08-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filler', '0008_rename_row_fields_template_raw_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iranpassport',
            name='issuing_authority',
            field=models.CharField(choices=[('authority1', 'Полковник\nОмид Нодехи'), ('authority2', 'Бригадный генерал\nАли Золгадри'), ('authority3', 'Бригадный генерал\nСадэг Резадуст')], default='authority1', max_length=10, verbose_name='Имя и должность должностного лица'),
        ),
    ]
